"""initial TSCO platform schema

Revision ID: 2c30c15720e2
Revises: 
Create Date: 2026-08-05 19:13:23.761641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c30c15720e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('contact_email', sa.String(length=180), nullable=False),
    sa.Column('contact_phone', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('laboratory_name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=80), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('rated_mva', sa.Float(), nullable=True),
    sa.Column('station_name', sa.String(length=160), nullable=False),
    sa.Column('asset_location_label', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'asset_code', name='uq_asset_client_code')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=False)
    op.create_index(op.f('ix_assets_client_id'), 'assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'number', name='uq_quote_client_number')
    )
    op.create_index(op.f('ix_quotations_client_id'), 'quotations', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotations_number'), 'quotations', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=260), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('operations_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_states_site_id'), 'operations_states', ['site_id'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'number', name='uq_po_client_number')
    )
    op.create_index(op.f('ix_purchase_orders_client_id'), 'purchase_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_number'), 'purchase_orders', ['number'], unique=False)
    op.create_table('user_client_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_user_client_assignment')
    )
    op.create_index(op.f('ix_user_client_assignments_client_id'), 'user_client_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_client_assignments_user_id'), 'user_client_assignments', ['user_id'], unique=False)
    op.create_table('sampling_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sampling_orders_client_id'), 'sampling_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_sampling_orders_created_by_id'), 'sampling_orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_sampling_orders_order_number'), 'sampling_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_sampling_orders_site_id'), 'sampling_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_sampling_orders_status'), 'sampling_orders', ['status'], unique=False)
    op.create_index(op.f('ix_sampling_orders_supervisor_id'), 'sampling_orders', ['supervisor_id'], unique=False)
    op.create_table('sampling_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('assigned_sampler_id', sa.Integer(), nullable=True),
    sa.Column('assignment_code', sa.String(length=32), nullable=False),
    sa.Column('source_party', sa.String(length=30), nullable=False),
    sa.Column('requested_package', sa.String(length=120), nullable=False),
    sa.Column('sampling_point', sa.String(length=100), nullable=False),
    sa.Column('container_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_sample_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_sampler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sampling_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sampling_assignments_asset_id'), 'sampling_assignments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sampling_assignments_assigned_sampler_id'), 'sampling_assignments', ['assigned_sampler_id'], unique=False)
    op.create_index(op.f('ix_sampling_assignments_assignment_code'), 'sampling_assignments', ['assignment_code'], unique=True)
    op.create_index(op.f('ix_sampling_assignments_order_id'), 'sampling_assignments', ['order_id'], unique=False)
    op.create_index(op.f('ix_sampling_assignments_status'), 'sampling_assignments', ['status'], unique=False)
    op.create_table('sample_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=40), nullable=False),
    sa.Column('public_token', sa.String(length=80), nullable=False),
    sa.Column('barcode_value', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sampler_id', sa.Integer(), nullable=False),
    sa.Column('sampling_assignment_id', sa.Integer(), nullable=True),
    sa.Column('submission_channel', sa.String(length=30), nullable=False),
    sa.Column('sample_date_time', sa.DateTime(), nullable=False),
    sa.Column('sampling_point', sa.String(length=100), nullable=False),
    sa.Column('requested_package', sa.String(length=120), nullable=False),
    sa.Column('oil_temperature_c', sa.Float(), nullable=True),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=True),
    sa.Column('ambient_humidity_pct', sa.Float(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('field_notes', sa.Text(), nullable=False),
    sa.Column('container_count', sa.Integer(), nullable=False),
    sa.Column('lms_number', sa.String(length=80), nullable=True),
    sa.Column('client_sample_reference', sa.String(length=100), nullable=False),
    sa.Column('data_entry_note', sa.Text(), nullable=False),
    sa.Column('return_reason', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['sampler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sampling_assignment_id'], ['sampling_assignments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_requests_asset_id'), 'sample_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_barcode_value'), 'sample_requests', ['barcode_value'], unique=True)
    op.create_index(op.f('ix_sample_requests_client_id'), 'sample_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_lms_number'), 'sample_requests', ['lms_number'], unique=False)
    op.create_index(op.f('ix_sample_requests_public_token'), 'sample_requests', ['public_token'], unique=True)
    op.create_index(op.f('ix_sample_requests_request_number'), 'sample_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_sample_requests_sample_date_time'), 'sample_requests', ['sample_date_time'], unique=False)
    op.create_index(op.f('ix_sample_requests_sampler_id'), 'sample_requests', ['sampler_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_sampling_assignment_id'), 'sample_requests', ['sampling_assignment_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_site_id'), 'sample_requests', ['site_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_status'), 'sample_requests', ['status'], unique=False)
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key('fk_assignment_completed_sample', 'sampling_assignments', 'sample_requests', ['completed_sample_id'], ['id'])
    op.create_table('custody_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_request_id'], ['sample_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_events_event_at'), 'custody_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_custody_events_event_type'), 'custody_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_custody_events_sample_request_id'), 'custody_events', ['sample_request_id'], unique=False)
    op.create_index(op.f('ix_custody_events_status'), 'custody_events', ['status'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_request_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_request_id'], ['sample_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_issue_type'), 'data_quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_sample_request_id'), 'data_quality_issues', ['sample_request_id'], unique=False)
    op.create_table('lms_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_request_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=False),
    sa.Column('response_payload', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_request_id'], ['sample_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_sync_logs_sample_request_id'), 'lms_sync_logs', ['sample_request_id'], unique=False)
    op.create_table('sample_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_request_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('original_name', sa.String(length=220), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_request_id'], ['sample_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_photos_sample_request_id'), 'sample_photos', ['sample_request_id'], unique=False)
    op.create_table('technical_assessment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_request_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=80), nullable=False),
    sa.Column('system_findings_json', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_request_id'], ['sample_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_assessment_records_decision'), 'technical_assessment_records', ['decision'], unique=False)
    op.create_index(op.f('ix_technical_assessment_records_sample_request_id'), 'technical_assessment_records', ['sample_request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_assessment_records_sample_request_id'), table_name='technical_assessment_records')
    op.drop_index(op.f('ix_technical_assessment_records_decision'), table_name='technical_assessment_records')
    op.drop_table('technical_assessment_records')
    op.drop_index(op.f('ix_sample_photos_sample_request_id'), table_name='sample_photos')
    op.drop_table('sample_photos')
    op.drop_index(op.f('ix_lms_sync_logs_sample_request_id'), table_name='lms_sync_logs')
    op.drop_table('lms_sync_logs')
    op.drop_index(op.f('ix_data_quality_issues_sample_request_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_issue_type'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_custody_events_status'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_sample_request_id'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_event_type'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_event_at'), table_name='custody_events')
    op.drop_table('custody_events')
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint('fk_assignment_completed_sample', 'sampling_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_sample_requests_status'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_site_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_sampling_assignment_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_sampler_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_sample_date_time'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_request_number'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_public_token'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_lms_number'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_client_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_barcode_value'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_asset_id'), table_name='sample_requests')
    op.drop_table('sample_requests')
    op.drop_index(op.f('ix_sampling_assignments_status'), table_name='sampling_assignments')
    op.drop_index(op.f('ix_sampling_assignments_order_id'), table_name='sampling_assignments')
    op.drop_index(op.f('ix_sampling_assignments_assignment_code'), table_name='sampling_assignments')
    op.drop_index(op.f('ix_sampling_assignments_assigned_sampler_id'), table_name='sampling_assignments')
    op.drop_index(op.f('ix_sampling_assignments_asset_id'), table_name='sampling_assignments')
    op.drop_table('sampling_assignments')
    op.drop_index(op.f('ix_sampling_orders_supervisor_id'), table_name='sampling_orders')
    op.drop_index(op.f('ix_sampling_orders_status'), table_name='sampling_orders')
    op.drop_index(op.f('ix_sampling_orders_site_id'), table_name='sampling_orders')
    op.drop_index(op.f('ix_sampling_orders_order_number'), table_name='sampling_orders')
    op.drop_index(op.f('ix_sampling_orders_created_by_id'), table_name='sampling_orders')
    op.drop_index(op.f('ix_sampling_orders_client_id'), table_name='sampling_orders')
    op.drop_table('sampling_orders')
    op.drop_index(op.f('ix_user_client_assignments_user_id'), table_name='user_client_assignments')
    op.drop_index(op.f('ix_user_client_assignments_client_id'), table_name='user_client_assignments')
    op.drop_table('user_client_assignments')
    op.drop_index(op.f('ix_purchase_orders_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_client_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_operations_states_site_id'), table_name='operations_states')
    op.drop_table('operations_states')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quotations_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_client_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_client_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
